### PR TITLE
statika submission - write reply, modify abstract

### PR DESCRIPTION
**Pull request by eparejatobes**

### CODE REVIEW

**Comment by eparejatobes** [comment]
@marina-manrique @rtobes WDYT?

**Comment by marina-manrique** [comment]
I think it's OK

**Comment by rtobes** [comment]
The abstract is much better now because it is easy tio understand the utility of the tool but the reply is very short and I do not remember the "reviewer" comments

**Comment by eparejatobes** [comment]
@rtobes they are in the readme

**Comment by rtobes** [comment]
I have read the comments and I think now that your reply is OK (and the length enought considering the reviewer comment)

**Comment by eparejatobes** [comment]
:) you know, I'm good at being nice

**Pull request merged**
