### PR TITLE
Preparing slides for the Bio4j oral presentation

### PR DESCRIPTION
**Pull request by laughedelic**
If I am presenting this, I want to take @pablopareja's [FOSDEM presentation](http://ohnosequences.com/slides/fosdem-2014/bio4j-bigger-faster-leaner) and rework it to make shorter and more concise. 

From the [IWBBIO website](http://iwbbio.ugr.es/presentation.php):

> dedicate around 15 minutes to the oral presentation of your work and 3 minutes for questions

### CODE REVIEW

**Comment by laughedelic** [comment]
Ok, I think I've finished more or less working on the content. It is now around 17 slides (effectively). Maybe they need some better structuring though. As it is now:
- Introduction
  - what is bio4j
  - which data it integrates
  - it's open!
  - biology & databases today _(3-4 slides about the evil relational model)_
  - why graph db is better
  - why Bio4j _(maybe too concise and should be somewhere else)_
- Details about Bio4j
  - history _(not sure if I should include it)_
  - more data (continuing history) + big numbers
  - bio4j modules structure _(maybe should be extended)_
  - API layers of bio4j
  - AWS cloud (very shortly)
- Under the hood 
  - how era7 uses bio4j _(I'm not sure about it)_
  - how we develop bio4j _(maybe too technical for this conference?)_
  - ohnosequences team
  - contacts _(may be better to put clickable logos there?)_ 

@ohnosequences/members I would appreciate any feedback

**Comment by marina-manrique** [comment]
@laughedelic I'm going crazy trying to find the PDF with the slides, could you post here a link to it pls?

Thanks!!

**Comment by laughedelic** [comment]
@marina-manrique here: https://github.com/ohnosequences/IWBBIO-2014/blob/talk/slides/bio4j/bio4j/slides/slides.pdf

**Comment by marina-manrique** [comment]
:+1:  Thanks!

**Comment by marina-manrique** [comment]
I've already checked the slides, everything's alright to me! :)

**Comment by laughedelic** [comment]
@marina-manrique thanks!

**Comment by laughedelic** [comment]
:ok_hand:  
https://twitter.com/dameisen/status/453517532583186433

**Pull request merged**
